<?php
  function cards_menu() {
    $friends = [
      'Erica',
      'Michaela',
      'Cameron',
      'Bobert',
    ];
    foreach ($friends as $key) {
      $items['cards/' . $key] = array(
          'title' => $key,
          'page callback' => 'cards',
          'page arguments' => array($key),
          'access callback' => TRUE,
          'type' => MENU_NORMAL_ITEM,
      );
    }
    return $items;

  }

  function cards($key) {
    $greeting = 'Happy Birthday to ' . $key;

    return $greeting;
  }
